# Generated by Django 4.2.23 on 2025-06-25 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplication',
            name='agree_data_processing',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='convicted',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='read_terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='under_investigation',
        ),
    ]
