# Generated by Django 4.2.23 on 2025-06-25 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_remove_candidateapplication_agree_data_processing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplication',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='children_first',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='cpr_cert',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='elder_abuse',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='emergency_name',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='emergency_relationship',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='fetac_level_5',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='fire_safety',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='gdpr',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='hand_hygiene',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='hep_b',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='infection_control',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='mmr_immunity',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='nmbi_cert',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='patient_moving',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='ppe_training',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='safeguarding_adults',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='social_care_cert',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='student_nurse_id',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='varicella_immunity',
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.candidateapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_nurse_id', models.BooleanField(default=False)),
                ('nmbi_cert', models.BooleanField(default=False)),
                ('fetac_level_5', models.BooleanField(default=False)),
                ('social_care_cert', models.BooleanField(default=False)),
                ('cpr_cert', models.BooleanField(default=False)),
                ('patient_moving', models.BooleanField(default=False)),
                ('elder_abuse', models.BooleanField(default=False)),
                ('ppe_training', models.BooleanField(default=False)),
                ('infection_control', models.BooleanField(default=False)),
                ('safeguarding_adults', models.BooleanField(default=False)),
                ('hand_hygiene', models.BooleanField(default=False)),
                ('fire_safety', models.BooleanField(default=False)),
                ('children_first', models.BooleanField(default=False)),
                ('gdpr', models.BooleanField(default=False)),
                ('hep_b', models.BooleanField(default=False)),
                ('mmr_immunity', models.BooleanField(default=False)),
                ('varicella_immunity', models.BooleanField(default=False)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.candidateapplication')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.candidateapplication')),
            ],
        ),
    ]
