# Generated by Django 4.2.23 on 2025-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_remove_candidateapplication_bic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=10)),
                ('forenames', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('phone_mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('eircode', models.CharField(max_length=10)),
                ('pps_number', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('eu_passport_or_gnib', models.BooleanField(default=False)),
                ('emergency_name', models.CharField(max_length=100)),
                ('emergency_relationship', models.CharField(max_length=50)),
                ('emergency_phone', models.CharField(max_length=20)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bic', models.CharField(blank=True, max_length=11)),
                ('student_nurse_id', models.BooleanField(default=False)),
                ('nmbi_cert', models.BooleanField(default=False)),
                ('fetac_level_5', models.BooleanField(default=False)),
                ('social_care_cert', models.BooleanField(default=False)),
                ('cpr_cert', models.BooleanField(default=False)),
                ('patient_moving', models.BooleanField(default=False)),
                ('elder_abuse', models.BooleanField(default=False)),
                ('ppe_training', models.BooleanField(default=False)),
                ('infection_control', models.BooleanField(default=False)),
                ('safeguarding_adults', models.BooleanField(default=False)),
                ('hand_hygiene', models.BooleanField(default=False)),
                ('fire_safety', models.BooleanField(default=False)),
                ('children_first', models.BooleanField(default=False)),
                ('gdpr', models.BooleanField(default=False)),
                ('hep_b', models.BooleanField(default=False)),
                ('mmr_immunity', models.BooleanField(default=False)),
                ('varicella_immunity', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certification',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='candidate',
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
        migrations.DeleteModel(
            name='CandidateApplication',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='EmergencyContact',
        ),
    ]
