# Generated by Django 4.2.23 on 2025-06-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_employeeapplication_remove_certification_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeapplication',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
